export enum RespondTaskDialogType {
    RESPONSE = 'RESPONSE',
    EDIT_RESPONSE = 'EDIT_RESPONSE',
    RESPONSE_WITH_COURT_APPOINTMENT = 'RESPONSE_WITH_COURT_APPOINTMENT',
    EDIT_RESPONSE_WITH_COURT_APPOINTMENT = 'EDIT_RESPONSE_WITH_COURT_APPOINTMENT',
}