export class UserModel{
    id:string;
    email:string;
    role:string;
    companyId:string;
    firstName:string;
    fatherName:string;
    grandFatherName:string;
    familyName:string;
    phoneNumber:string;
    address:string;
    dateOfBirth:Date;
    placeOfBirth:Date;
    education:string;
    experience:string;
    skills:string;
    nationality:string;
    profilePicture:string;
    createdBy:string;
    createdTime:Date;
    updatedTime:Date;
    isActive:boolean;
    isDeleted:boolean;
    isCompanyCreated:boolean;
    isFtl:boolean;
    mobileNumber:string;
    jobId : string;
    roleId : string;
    deptId :string;
}
